server:
  port: 8082
  servlet:
    context-path: /api/content

spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://mysql:3306/content
    username: root
    password: 1234

