server:
  port: 8082
  servlet:
    context-path: /api/product-content

spring:
  rabbitmq:
    # todo: fix docker containers interconnection
    host: 10.135.26.20
    port: 5672
    username: guest
    password: guest

