version : '2'
services:
  content-service:
    container_name: content-service
    tty: true
    build: ../
    ports:
      - "8082:8082"
      - "4082:4082"
    volumes:
      - ../build/libs:/vol/development/